FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY config.example.js /usr/share/nginx/html/config.example.js

# Startup script writes config.js from GOOGLE_MAPS_KEY env var
RUN echo '#!/bin/sh' > /docker-entrypoint.d/40-config.sh \
 && echo 'echo "window.GOOGLE_MAPS_KEY = '"'"'${GOOGLE_MAPS_KEY}'"'"';" > /usr/share/nginx/html/config.js' >> /docker-entrypoint.d/40-config.sh \
 && chmod +x /docker-entrypoint.d/40-config.sh
